#debug: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN
    org.manuelarriola.demos: ALL
    
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://disco-srv:9899/eureka/

zuul:
  routes:
    api:      
      sensitiveHeaders: 
      url: http://api-srv:8081
      serviceId: clientes-api
      