server:
  port: 8081
spring:
    data:
        mongodb:
            host: mongo-srv
            port: 27017
            authentication-database: admin
            username: mongoadmin
            password: secret
            database: mag